services:
  php:
    build:
      context: .
      dockerfile: environment/php/Dockerfile
      args:
        LOCAL_USER_ID_ARG: ${LOCAL_USER_ID}
        LOCAL_GROUP_ID_ARG: ${LOCAL_GROUP_ID}
    depends_on:
      - db
    volumes:
      - ./:/home/www-data/application:rw
    networks:
      - internal
    env_file:
      - .env
  db:
    image: mariadb:11.2.2
    networks:
      - internal
    env_file:
      - .env
networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNETWORK}
